### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by Diegovsky** [cdbbnnyCode/modpack-installer#1]
Hey there! I just found your project and it is really neato :D
It works nicely with forge but I tried to download a fabric modpack and learned it isn't possible yet. Do you think it is possible to add support for fabric?

**Comment by cdbbnnyCode** [comment]
I'll definitely look into this, since Fabric is pretty popular and supporting it shouldn't be too difficult.

After a cursory look at the Fabric installer, it appears that it has command-line install options, which should make things very simple. However, I have no experience with the Fabric loader and I'd have to do some experimenting to figure out what works.

**Comment by Diegovsky** [comment]
I can look into it and submit a draft PR. What do you think?

**Comment by cdbbnnyCode** [comment]
Sure, go ahead! I haven't started working on this yet, so if you have an idea, feel free to submit a PR.

**Comment by Diegovsky** [comment]
Alright, I'll be looking into it then :)

**Comment by cdbbnnyCode** [comment]
I finally found some time to work on this. Fabric support is working and has been tested on 2 modpacks (All of Fabric 3 and 4). Resolved in commit 41d088e.

**Comment by Diegovsky** [comment]
Nice work! I got busy this week with unprecedented school assignments, but I'll definitely check it out as soon as I'm able to :)
