### ISSUE TITLE
Suggestion: Use a python formatter (such as black)

### ISSUE THREAD

**Issue by PraxTube** [cdbbnnyCode/modpack-installer#29]
I would strongly advise to use a formatter. The code base is rather inconsistent and could benefit from a formatter (i.e. [black](https://pypi.org/project/black/). In the same vein it would also be a good idea to set up some github actions to check for formatting issues automatically (and maybe even add tests).

It's way easier if the code base would use more conventional code formatting and makes it easier for new people to modify and read the code.

The main problem is that the incorporation of a formatter would create many merge conflicts with existing PRs. I would suggest to either finish all PRs in one go and merge them, or format the code base gradually.

**Comment by cdbbnnyCode** [comment]
I do not see the need for an auto-formatter for the codebase. While I do agree that the formatting could be improved slightly, there is nothing I can see that would make it difficult to read or contribute to. This code is likely never going to be fully PEP-8 compliant, and I see no real benefit in enforcing such rules.

If this project gains significantly more traction in the future, I might add some formatting conventions in order to maintain some level of consistency from external contributions. However, in its current state, I don't see much value in enforcing strict style rules on such a small project.
