### ISSUE TITLE
Symbolic links to mods do not seem to work

### ISSUE THREAD

**Issue by Leroymilo** [cdbbnnyCode/modpack-installer#31]
I am on Fedora Linux, I downloaded the Minecraft launcher from the fedora "app store", the **main** .minecraft folder is located at ~/.var/app/com.mojang.Minecraft/.minecraft .
After updating java, your app worked and created the .minecraft, every symbolic link and the minecraft version in the launcher, but once I launched Minecraft with this new version, it said "2 mods loaded".
**Copying the symolic links** to mods into the **main .minecraft/mods seemed** to have no effect,
**Replacing the symbolic links with the actual mods .jar files** into the **new .minecraft/mods** created did not either.

I fixed it by **copying the actual mods .jar files** into the **main .minecraft/mods** folder.

**Comment by cdbbnnyCode** [comment]
If you're using Forge, make sure you're using the installation that has the same name as the modpack, and not the "forge" installation (which points to the default `.minecraft` path). Otherwise, there might be something else strange going on; I've never seen an issue like this.

Could you share which modpack you're trying to install? There is a small chance that it might have something to do with that.

**Comment by Leroymilo** [comment]
Yes, I made sure to launch the installation with the name of the modpack. Here is the modpack page : https://www.curseforge.com/minecraft/modpacks/auto-terrafirmacraft-tfc-create .

It does work perfectly now that I've copied the .jar files in the main mods folder, so it would be weird that the modpack is the reason of this issue.

**Comment by cdbbnnyCode** [comment]
There is a chance that the specific combination of Minecraft version and modloader version used by the modpack would cause symlinks to not be recognized; that's why I was wondering about the specific modpack. However, I did test just now and that modpack works on my system.

After some checking, this most likely actually has to do with Flatpak (which the Fedora app store is based on), which has a sandbox preventing the game from accessing the mod files outside of the installation directory: [https://docs.flatpak.org/en/latest/sandbox-permissions.html](https://docs.flatpak.org/en/latest/sandbox-permissions.html). I am going to try installing the launcher with Flatpak and see if I can set it up to have permission to access outside its sandbox.

In the meantime, using the launcher tarball provided at [https://www.minecraft.net/en-us/download](https://www.minecraft.net/en-us/download) should work correctly.

**Comment by cdbbnnyCode** [comment]
Actually, it should be possible to detect if Flatpak is being used and move `.modcache` and `packs/` into the app filesystem automatically.

**Comment by cdbbnnyCode** [comment]
Should be fixed in the latest commit (2dc032e)

**Comment by Leroymilo** [comment]
Thanks, I updated the modpack I'm playing on and it seems to works pretty well, I just had some trouble finding where the modpack was installed to copypaste my save.
