### ISSUE TITLE
FileNotFoundError: [Errno 2] ....'manifest.json'

### ISSUE THREAD

**Issue by julesderallerechte** [cdbbnnyCode/modpack-installer#7]
Hello,
I'm stuck here with this error link to a missing file. Any idea how I can move forward ?
BR
Jules

:~/Downloads/modpack-installer-master$ python3 install.py RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip
Extracting RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip
Creating .minecraft directory
Creating symlinks
Creating launcher profiles
Installing modloader
Traceback (most recent call last):
  File "install.py", line 90, in main
    with open(packdata_dir + '/manifest.json', 'r') as mf:
FileNotFoundError: [Errno 2] No such file or directory: '.packs/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2/manifest.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "install.py", line 196, in <module>
    main(args.zipfile, args.forge_disable)
  File "install.py", line 92, in main
    except (json.JsonDecodeError, OSError) as e:
AttributeError: module 'json' has no attribute 'JsonDecodeError'

**Comment by cdbbnnyCode** [comment]
You downloaded the server pack; this program is only for client-side modpacks.
* If you were wanting to play RLCraft single-player, try downloading the zip file 'RLCraft Beta v2.8.2' from CurseForge instead.
* If you were wanting to set up a server, just extract your server pack zip file and use the Minecraft Forge installer jar to "install server" onto it.

Server packs contain all of the mods directly (which is why they are so large), and (presumably) you can just run the Minecraft Forge installer jar and "install server" to the extracted location.

Client-side modpacks, however, contain only configuration files and a list of references to all of the mods that they use (the `manifest.json` file.) This installer program's main function is to parse that mod list and fetch all of the required data from CurseForge's servers.

Since the server pack doesn't have this `manifest.json` file, the program can't find it and it crashes.

Also, that `AttributeError` at the end looks like an actual bug. I will probably fix it later.
